### ISSUE TITLE
Undoing the changes

### ISSUE THREAD

**Issue by hullas1502** [Rahul5214/proxy_git_settings#1]
Hi! Thanks for the wonderful script. How do I reset the proxy settings to default?

**Comment by Rahul5214** [comment]
Hi
To set proxy to default edit these files,
In `/etc/environment`, comment all the line except line containing `PATH `variable. Comment all the line in `/etc/apt/apt.conf.d/99proxy `and `/etc/apt/apt.conf `file and change all the repo in `/etc/apt/sources.list `to default. Use this [link ](https://repogen.simplylinux.ch/) to generate defalt repo for your system
